### PR TITLE
Add support for doctrine/dbal ^4

### LINKED ISSUE #1: Support for doctrine/dbal v4
Hi, doctrine/dbal has sable version 4. It looks like this library is compatible with that version, but composer.json is limited to "^2.3 || ^3".

### PR DESCRIPTION
**Pull request by gndk**
Fixes #1 

Minimum PHP version needs to be 8.1, because the return type for `getBindingType()` changed from `int` to `enum`.

For the same reason, I don't see a way to support DBAL 2/3 and 4 at the same time. So this should probably be merged into a new `6.x` branch instead of main.

### CODE REVIEW

**Comment by gndk** [comment]
@zanbaldwin Can you take a look? 🙂

**Comment by niravpateljoin** [comment]
this PR looks good and compatible with DBAL 4.2, I am having similar issue, so @zanbaldwin can you please have a look on this PR, so we can merge this into the release? thank you.

**Comment by zanbaldwin** [comment]
Hi, yes. Sorry for the massive delay - it's been a busy quarter for me.
I'll get this done and start the `v6` branch for PHP `8.1` and above :+1:

**Review by zanbaldwin — APPROVED** [review]
Thanks for this! I'll add PHP 8.4 to the CI pipeline then release a new version.

**Comment by zanbaldwin** [comment]
@gndk would you like to add yourself to the authors section of the README before I push a new release?

**Comment by zanbaldwin** [comment]
- Version `^5` of this library will continue supporting DBAL `2.3+`/`3.0+` (and PHP `5.6+`)
- Version `^6` of this library now supports DBAL `4.0+` (and PHP `8.1+`)

Thanks for this PR adding DBAL4 support! :+1:

**Pull request merged**
